# Generated by Django 5.0.7 on 2024-08-06 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_xg_algo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DECISION_ALGO',
            fields=[
                ('S_NO', models.AutoField(primary_key=True, serialize=False)),
                ('Accuracy', models.TextField(max_length=100)),
                ('Precession', models.TextField(max_length=100)),
                ('F1_Score', models.TextField(max_length=100)),
                ('Recall', models.TextField(max_length=100)),
                ('Name', models.TextField(max_length=100)),
            ],
            options={
                'db_table': 'DECISION_ALGO',
            },
        ),
        migrations.AlterModelTable(
            name='ada_algo',
            table='ADA_ALGO',
        ),
    ]
